services:
  couchdb-obsidian-livesync:
    image: docker.io/oleduc/docker-obsidian-livesync-couchdb:latest@sha256:6a99266f794e23026018e0b6c5bd83fe21f35475c6fb3980283f7ee6371d95a1
    container_name: couchdb-obsidian-livesync
    restart: unless-stopped
    environment:
      SERVER_URL: ${SERVER_URL}
      COUCHDB_USER: ${COUCHDB_USER}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD}
      COUCHDB_DATABASE: ${COUCHDB_DATABASE}
    ports:
      - 5984:5984
    volumes:
      - ./data:/opt/couchdb/data

networks:
  default:
    name: caddy_proxy
    external: true
